formatter: "md table"

version: "0.20.0"

content: |-
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  ## Examples
  {{ .Outputs }}

output:
  file: README.md
  mode: replace
