name: build-and-push-container-image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Specify the image repository environment."
        required: true
        default: "dev"
      build-target:
        description: "Tag name of branch name to deploy (e.g. main, develop, v1.0.0 etc.)."
        required: true
        default: "main"

permissions:
  id-token: write
  contents: read
jobs:
  build-and-push-container-image:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.build-target }}

      - name: Get image tag
        id: get-image-tag
        run: |
          SHORT_COMMIT_ID=$(git rev-parse --short HEAD)
          REF=$(echo ${{ github.event.inputs.build-target }} | sed -e 's/\//-/g')
          echo "image-tag=${REF}-${SHORT_COMMIT_ID}" >> $GITHUB_OUTPUT

      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.IAM_ARN_TO_PUSH_IMAGE }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to Amazon ECR
        uses: docker/build-push-action@v6
        with:
          context: "docker/html"
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/sample-${{ github.event.inputs.environment }}-web:${{ steps.get-image-tag.outputs.image-tag }}
