name: Generate Terraform Docs on Pull Request

on:
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - modules/cloudwatch/logs
          - modules/ecr
          - modules/ecs/cluster
          - modules/ecs/iam/roles
          - modules/ecs/service
          - modules/ecs/service/alb
          - modules/ecs/task
          - modules/iam/provider/oidc/github
          - modules/iam/role/oidc/github
          - modules/vpc
          - modules/vpc/security_group
    outputs:
      changed: ${{ steps.set-changed.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Terraform docs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: ${{ matrix.directory }}
          config-file: ${{ github.workspace }}/.terraform-docs.yaml
          output-file: README.md
          git-push: false

      - name: Add README to staging
        run: |
          git add ${{ matrix.directory }}/README.md

  push-docs:
    needs: generate-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Commit and push all README.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update Terraform docs" || true
          git push origin ${{ github.event.pull_request.head.ref }}
