name: Generate Terraform Docs on Pull Request

on:
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Terraform docs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: modules/*
          recursive: true
          config-file: ${{ github.workspace }}/.terraform-docs.yaml
          output-file: README.md
          git-push: true
