
name: Generate Terraform Docs on Pull Request

on:
  pull_request:

jobs:
  generate-docs:
    name: Generate and Commit Terraform Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Find all Terraform module directories
        id: find_modules
        run: |
          find modules -type d | while read dir; do
            if find "$dir" -maxdepth 1 -name '*.tf' | grep -q .; then
              echo "$dir" >> modules_list.txt
            fi
          done

      - name: Generate Terraform docs and stage README.md
        run: |
          while read dir; do
            terraform-docs markdown table --config .terraform-docs.yaml --output-file README.md --output-mode inject "$dir"
            git add "$dir/README.md"
          done < modules_list.txt

      - name: Commit and push all README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --cached --quiet || git commit -m "Update Terraform docs"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
